name: my-store

services:
  db:
    image: postgres:16-alpine
    container_name: my-store-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: forushat
      POSTGRES_PASSWORD: forushat
      POSTGRES_DB: forushat
    ports:
      - "5433:5432"
    volumes:
      - my_store_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forushat -d forushat"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: my-store-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6380:6379"
    volumes:
      - my_store_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  my_store_pgdata:
  my_store_redisdata:
