import { Type } from 'class-transformer';
import { IsDateString, IsEnum, IsNumber, IsOptional, IsString, Max, MaxLength, Min } from 'class-validator';
import { PaginationQueryDto } from '../../../common/dto/pagination-query.dto';

/** Sanity cap on a register transaction/balance — guards against a typo (extra digit) */
const MAX_CASH_AMOUNT = 10_000_000_000;

/** Manual entry of income/expense/withdrawal — SALE and REFUND are only recorded by the system */
export class CreateCashTransactionDto {
  @IsEnum(['INCOME', 'EXPENSE', 'WITHDRAWAL'])
  type: 'INCOME' | 'EXPENSE' | 'WITHDRAWAL';

  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0.01)
  @Max(MAX_CASH_AMOUNT)
  amount: number;

  @IsOptional()
  @IsString()
  @MaxLength(80)
  category?: string;

  @IsOptional()
  @IsString()
  note?: string;

  /** Optional pay slip / receipt photo URL (from POST /uploads/cash-receipts) */
  @IsOptional()
  @IsString()
  receiptUrl?: string;

  /** The work session whose cash box paid / received this. Empty = the main cash box; not given = the user's own active session */
  @IsOptional()
  @IsString()
  sessionId?: string | null;

  /** When it happened — leave empty for now; a past date back-fills an old transaction (no future dates) */
  @IsOptional()
  @IsDateString()
  date?: string;
}

export class CashTransactionListQueryDto extends PaginationQueryDto {
  @IsOptional()
  @IsEnum(['SALE', 'INCOME', 'EXPENSE', 'REFUND', 'WITHDRAWAL'])
  type?: 'SALE' | 'INCOME' | 'EXPENSE' | 'REFUND' | 'WITHDRAWAL';

  /** e.g. "salary" or "partner" — filters to cash effects generated by that feature */
  @IsOptional()
  @IsString()
  referenceType?: string;
}

export class IncomeSummaryQueryDto {
  /** Range start — defaults to the first day of the current month */
  @IsOptional()
  @IsDateString()
  from?: string;

  /** Range end (whole day included) — defaults to now */
  @IsOptional()
  @IsDateString()
  to?: string;

  @IsOptional()
  @IsString()
  branchId?: string;
}
