import { Type } from 'class-transformer';
import {
  IsBoolean,
  IsEnum,
  IsNumber,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
  MinLength,
} from 'class-validator';

/** Sanity cap on a register transaction/balance — guards against a typo (extra digit) */
const MAX_CASH_AMOUNT = 10_000_000_000;
import { PaginationQueryDto } from '../../../common/dto/pagination-query.dto';

export class CreateCashRegisterDto {
  @IsString()
  branchId: string;

  @IsString()
  @MinLength(2)
  @MaxLength(80)
  name: string;

  @IsOptional()
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  @Max(MAX_CASH_AMOUNT)
  openingBalance?: number;

  @IsOptional()
  @IsBoolean()
  isDefault?: boolean;

  /** This register = the branch's net sale profit register — receives the full profit share of each sale */
  @IsOptional()
  @IsBoolean()
  isNetProfitBox?: boolean;
}

export class UpdateCashRegisterDto {
  @IsOptional()
  @IsString()
  @MinLength(2)
  @MaxLength(80)
  name?: string;

  @IsOptional()
  @IsBoolean()
  isDefault?: boolean;

  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  @IsOptional()
  @IsBoolean()
  isNetProfitBox?: boolean;
}

/** Manual entry of income/expense/withdrawal — SALE and REFUND are only recorded by the system */
export class CreateCashTransactionDto {
  @IsEnum(['INCOME', 'EXPENSE', 'WITHDRAWAL'])
  type: 'INCOME' | 'EXPENSE' | 'WITHDRAWAL';

  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0.01)
  @Max(MAX_CASH_AMOUNT)
  amount: number;

  @IsOptional()
  @IsString()
  @MaxLength(80)
  category?: string;

  @IsOptional()
  @IsString()
  note?: string;
}

export class CashTransactionListQueryDto extends PaginationQueryDto {
  @IsOptional()
  @IsEnum(['SALE', 'INCOME', 'EXPENSE', 'REFUND', 'WITHDRAWAL'])
  type?: 'SALE' | 'INCOME' | 'EXPENSE' | 'REFUND' | 'WITHDRAWAL';

  /** e.g. "salary" or "partner" — filters to cash effects generated by that feature */
  @IsOptional()
  @IsString()
  referenceType?: string;
}
