'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, TrendingUp, Vault } from 'lucide-react';
import { useLocale, useTranslations } from 'next-intl';
import { FormEvent, useState } from 'react';
import type {
  BranchDto,
  CashRegisterDto,
  CashTransactionDto,
  CashTransactionType,
  EmployeeDto,
  Locale,
  PartnerDto,
  SellerDto,
} from '@my-store/shared';
import { api } from '@/lib/api-client';
import { formatDate, formatMoney, formatNumber } from '@/lib/format';
import { Badge, Button, Card, ErrorText, Field, Input, Modal, Select, Spinner, cn } from '@/components/ui';
import { ExportButtons } from '@/components/export-buttons';

/** Manually recordable types — SALE/REFUND are generated by the system */
const MANUAL_TX_TYPES: CashTransactionType[] = ['INCOME', 'EXPENSE', 'WITHDRAWAL'];

const TX_TONES: Record<CashTransactionType, string> = {
  SALE: 'APPROVED',
  INCOME: 'APPROVED',
  EXPENSE: 'danger',
  REFUND: 'danger',
  WITHDRAWAL: 'RETURNED',
};

export default function CashPage() {
  const t = useTranslations('cash');
  const tc = useTranslations('common');
  const locale = useLocale() as Locale;
  const queryClient = useQueryClient();

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [newRegister, setNewRegister] = useState(false);
  const [newTx, setNewTx] = useState(false);

  const { data: registers, isPending, error } = useQuery({
    queryKey: ['cash-registers'],
    queryFn: () => api.get<CashRegisterDto[]>('/cash-registers'),
  });

  const selected = registers?.find((r) => r.id === selectedId) ?? registers?.[0] ?? null;

  const setNetProfitBox = useMutation({
    mutationFn: (id: string) => api.patch(`/cash-registers/${id}`, { isNetProfitBox: true }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['cash-registers'] }),
  });

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h1 className="text-xl font-black text-ink">{t('title')}</h1>
        <div className="flex flex-wrap gap-2">
          <ExportButtons path="/exports/cash" />
          <Button onClick={() => setNewRegister(true)}>
            <Plus className="h-4 w-4" aria-hidden />
            {t('newRegister')}
          </Button>
        </div>
      </div>

      <ErrorText error={error} />
      <ErrorText error={setNetProfitBox.error} />
      {isPending ? (
        <Spinner />
      ) : (
        <>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {registers?.map((register) => (
              <div
                key={register.id}
                role="button"
                tabIndex={0}
                onClick={() => setSelectedId(register.id)}
                onKeyDown={(e) => e.key === 'Enter' && setSelectedId(register.id)}
                className={cn(
                  'cursor-pointer rounded-xl border p-4 text-start transition-colors',
                  selected?.id === register.id
                    ? 'border-primary-500 bg-primary-50 dark:bg-primary-900/20'
                    : 'border-line bg-surface-2 hover:border-primary-300',
                )}
              >
                <div className="flex items-center justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <Vault className="h-4 w-4 text-primary-600" aria-hidden />
                    <span className="font-bold text-ink">{register.name}</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    {register.isDefault && <Badge tone="APPROVED">{t('default')}</Badge>}
                    {register.isNetProfitBox && <Badge tone="neutral">{t('netProfitBox')}</Badge>}
                  </div>
                </div>
                <p className="mt-1 text-xs text-ink-faint">{register.branchName}</p>
                <p className="mt-2 text-lg font-black text-ink">
                  {formatMoney(register.balance, locale)}{' '}
                  <span className="text-xs font-normal text-ink-faint">{tc('currency')}</span>
                </p>
                <div className="mt-2 flex flex-wrap gap-3">
                  {!register.isNetProfitBox && (
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        setNetProfitBox.mutate(register.id);
                      }}
                      disabled={setNetProfitBox.isPending}
                      className="flex cursor-pointer items-center gap-1 text-xs font-semibold text-primary-700 transition-colors hover:text-primary-800 disabled:opacity-50 dark:text-primary-300 dark:hover:text-primary-200"
                    >
                      <TrendingUp className="h-3.5 w-3.5" aria-hidden />
                      {t('makeNetProfitBox')}
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>

          {selected && (
            <RegisterTransactions register={selected} onNewTx={() => setNewTx(true)} />
          )}
        </>
      )}

      {newRegister && <RegisterModal onClose={() => setNewRegister(false)} />}
      {newTx && selected && <TransactionModal register={selected} onClose={() => setNewTx(false)} />}
    </div>
  );
}

const REFERENCE_FILTERS = ['', 'salary', 'partner'] as const;

function RegisterTransactions({
  register,
  onNewTx,
}: {
  register: CashRegisterDto;
  onNewTx: () => void;
}) {
  const t = useTranslations('cash');
  const tc = useTranslations('common');
  const locale = useLocale() as Locale;
  const [page, setPage] = useState(1);
  const [referenceType, setReferenceType] = useState<(typeof REFERENCE_FILTERS)[number]>('');

  const { data, isPending, error } = useQuery({
    queryKey: ['cash-transactions', register.id, page, referenceType],
    queryFn: () =>
      api.getPaged<CashTransactionDto[]>(
        `/cash-registers/${register.id}/transactions?page=${page}&limit=15${referenceType ? `&referenceType=${referenceType}` : ''}`,
      ),
  });

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h2 className="text-base font-bold text-ink">
          {t('transactionsOf', { name: register.name })}
        </h2>
        <div className="flex flex-wrap items-center gap-2">
          <Select
            value={referenceType}
            onChange={(e) => {
              setReferenceType(e.target.value as (typeof REFERENCE_FILTERS)[number]);
              setPage(1);
            }}
            className="!min-h-9 !py-1 text-sm"
          >
            {REFERENCE_FILTERS.map((ref) => (
              <option key={ref} value={ref}>
                {t(`referenceFilters.${ref || 'all'}`)}
              </option>
            ))}
          </Select>
          <Button variant="outline" onClick={onNewTx}>
            <Plus className="h-4 w-4" aria-hidden />
            {t('newTransaction')}
          </Button>
        </div>
      </div>

      <ErrorText error={error} />
      {isPending ? (
        <Spinner />
      ) : (
        <Card className="overflow-x-auto">
          <table className="w-full min-w-[640px] text-sm">
            <thead>
              <tr className="border-b border-line text-xs text-ink-muted">
                <th className="p-3 text-start font-medium">{t('txType')}</th>
                <th className="p-3 text-start font-medium">{t('amount')}</th>
                <th className="p-3 text-start font-medium">{t('balanceAfter')}</th>
                <th className="p-3 text-start font-medium">{t('note')}</th>
                <th className="p-3 text-start font-medium">{t('performedBy')}</th>
                <th className="p-3 text-start font-medium">{t('date')}</th>
              </tr>
            </thead>
            <tbody>
              {data?.items.length === 0 && (
                <tr>
                  <td colSpan={6} className="p-8 text-center text-ink-faint">
                    {tc('noData')}
                  </td>
                </tr>
              )}
              {data?.items.map((tx) => (
                <tr key={tx.id} className="border-b border-line/60 last:border-0">
                  <td className="p-3">
                    <Badge tone={TX_TONES[tx.type]}>{t(`txTypes.${tx.type}`)}</Badge>
                  </td>
                  <td className="p-3 font-bold text-ink">{formatMoney(tx.amount, locale)}</td>
                  <td className="p-3 text-ink-muted">{formatMoney(tx.balanceAfter, locale)}</td>
                  <td className="p-3 text-ink-muted">{tx.category ?? tx.note ?? '—'}</td>
                  <td className="p-3 text-ink-muted">{tx.performedByName}</td>
                  <td className="p-3 text-xs text-ink-faint">{formatDate(tx.createdAt, locale)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
      )}

      {data && data.meta.totalPages > 1 && (
        <div className="flex items-center justify-between">
          <Button variant="outline" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>
            {tc('prev')}
          </Button>
          <span className="text-sm text-ink-muted">
            {tc('page', {
              page: formatNumber(data.meta.page, locale),
              total: formatNumber(data.meta.totalPages, locale),
            })}
          </span>
          <Button
            variant="outline"
            disabled={page >= data.meta.totalPages}
            onClick={() => setPage((p) => p + 1)}
          >
            {tc('next')}
          </Button>
        </div>
      )}
    </div>
  );
}

function RegisterModal({ onClose }: { onClose: () => void }) {
  const t = useTranslations('cash');
  const tc = useTranslations('common');
  const queryClient = useQueryClient();
  const [branchId, setBranchId] = useState('');
  const [name, setName] = useState('');
  const [openingBalance, setOpeningBalance] = useState('');
  const [isNetProfitBox, setIsNetProfitBox] = useState(false);

  const { data: branches } = useQuery({
    queryKey: ['branches'],
    queryFn: () => api.get<BranchDto[]>('/branches'),
  });

  const mutation = useMutation({
    mutationFn: () =>
      api.post('/cash-registers', {
        branchId,
        name,
        openingBalance: openingBalance === '' ? undefined : Number(openingBalance),
        isNetProfitBox,
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cash-registers'] });
      onClose();
    },
  });

  function submit(e: FormEvent) {
    e.preventDefault();
    mutation.mutate();
  }

  return (
    <Modal open title={t('newRegister')} onClose={onClose}>
      <form onSubmit={submit} className="space-y-4">
        <Field label={t('branch')}>
          <Select required value={branchId} onChange={(e) => setBranchId(e.target.value)}>
            <option value="" disabled>
              {t('selectBranch')}
            </option>
            {branches?.map((b) => (
              <option key={b.id} value={b.id}>
                {b.name}
              </option>
            ))}
          </Select>
        </Field>
        <Field label={t('registerName')}>
          <Input required value={name} onChange={(e) => setName(e.target.value)} />
        </Field>
        <Field label={t('openingBalance')}>
          <Input type="number" min={0} step="0.01" dir="ltr" value={openingBalance} onChange={(e) => setOpeningBalance(e.target.value)} />
        </Field>
        <label className="flex cursor-pointer items-center gap-2 text-sm text-ink">
          <input
            type="checkbox"
            checked={isNetProfitBox}
            onChange={(e) => setIsNetProfitBox(e.target.checked)}
            className="h-4 w-4 cursor-pointer accent-primary-600"
          />
          {t('makeNetProfitBox')}
        </label>
        {isNetProfitBox && <p className="text-xs text-ink-faint">{t('netProfitBoxHint')}</p>}
        <ErrorText error={mutation.error} />
        <div className="flex gap-2">
          <Button type="submit" loading={mutation.isPending}>
            {tc('create')}
          </Button>
          <Button type="button" variant="ghost" onClick={onClose}>
            {tc('cancel')}
          </Button>
        </div>
      </form>
    </Modal>
  );
}

const SALARY_CATEGORY = 'Salary payment';
const PARTNER_CATEGORY = 'Partner withdrawal';

/** Selectable categories per transaction type — stored as-is in the transaction's category */
const CATEGORIES: Record<'INCOME' | 'EXPENSE' | 'WITHDRAWAL', { value: string; key: string }[]> = {
  INCOME: [
    { value: 'Other income', key: 'otherIncome' },
    { value: 'Capital injection', key: 'capitalInjection' },
    { value: 'Other', key: 'other' },
  ],
  EXPENSE: [
    { value: SALARY_CATEGORY, key: 'salary' },
    { value: 'Rent', key: 'rent' },
    { value: 'Utilities', key: 'utilities' },
    { value: 'Transport', key: 'transport' },
    { value: 'Supplies', key: 'supplies' },
    { value: 'Maintenance', key: 'maintenance' },
    { value: 'Marketing', key: 'marketing' },
    { value: 'Taxes & fees', key: 'taxes' },
    { value: 'Other', key: 'other' },
  ],
  WITHDRAWAL: [
    { value: PARTNER_CATEGORY, key: 'partner' },
    { value: 'Owner withdrawal', key: 'owner' },
    { value: 'Other', key: 'other' },
  ],
};

function currentPeriod() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

function TransactionModal({ register, onClose }: { register: CashRegisterDto; onClose: () => void }) {
  const t = useTranslations('cash');
  const tc = useTranslations('common');
  const te = useTranslations('employees');
  const locale = useLocale() as Locale;
  const queryClient = useQueryClient();
  const [type, setType] = useState<'INCOME' | 'EXPENSE' | 'WITHDRAWAL'>('EXPENSE');
  const [category, setCategory] = useState(CATEGORIES.EXPENSE[0].value);
  const [amount, setAmount] = useState('');
  const [note, setNote] = useState('');
  const [person, setPerson] = useState('');
  const [period, setPeriod] = useState(currentPeriod);
  const [receipt, setReceipt] = useState<File | null>(null);

  const isSalary = type === 'EXPENSE' && category === SALARY_CATEGORY;
  const isPartner = type === 'WITHDRAWAL' && category === PARTNER_CATEGORY;

  const { data: employees } = useQuery({
    queryKey: ['employees'],
    queryFn: () => api.get<EmployeeDto[]>('/employees'),
    enabled: isSalary,
  });
  const { data: sellers } = useQuery({
    queryKey: ['sellers'],
    queryFn: () => api.get<SellerDto[]>('/sellers'),
    enabled: isSalary,
  });
  const { data: partners } = useQuery({
    queryKey: ['partners'],
    queryFn: () => api.get<PartnerDto[]>('/partners'),
    enabled: isPartner,
  });

  const staff = [
    ...(employees ?? [])
      .filter((e) => e.isActive)
      .map((e) => ({ key: `emp:${e.id}`, name: e.fullName, payType: e.payType, salary: e.salary })),
    ...(sellers ?? [])
      .filter((s) => s.isActive && s.payType === 'FIXED_SALARY')
      .map((s) => ({
        key: `sel:${s.id}`,
        name: `${s.fullName} (${t('seller')})`,
        payType: s.payType,
        salary: s.fixedSalaryAmount ?? '',
      })),
  ];
  const selectedStaff = staff.find((p) => p.key === person);

  function changeType(next: 'INCOME' | 'EXPENSE' | 'WITHDRAWAL') {
    setType(next);
    setCategory(CATEGORIES[next][0].value);
    setPerson('');
  }

  function changeCategory(next: string) {
    setCategory(next);
    setPerson('');
  }

  function changePerson(key: string) {
    setPerson(key);
    const found = staff.find((p) => p.key === key);
    if (found && found.payType === 'FIXED_SALARY' && Number(found.salary) > 0) setAmount(String(Number(found.salary)));
  }

  const mutation = useMutation({
    mutationFn: async () => {
      const common = { amount: Number(amount), note: note || undefined };
      if (isSalary) {
        let receiptImageUrl: string | undefined;
        if (receipt) {
          const form = new FormData();
          form.append('file', receipt);
          receiptImageUrl = (await api.upload<{ url: string }>('/uploads/salary-receipts', form)).url;
        }
        const [kind, id] = person.split(':');
        const body = { ...common, period, registerId: register.id, receiptImageUrl };
        return kind === 'sel'
          ? api.post(`/sellers/${id}/salary-payments`, body)
          : api.post(`/employees/${id}/salary-payments`, { ...body, status: 'PAID' });
      }
      if (isPartner) {
        return api.post(`/partners/${person}/entries`, { type: 'WITHDRAWAL', ...common, registerId: register.id });
      }
      return api.post(`/cash-registers/${register.id}/transactions`, { type, ...common, category });
    },
    onSuccess: () => {
      for (const key of ['cash-registers', 'cash-transactions', 'salary-payments', 'partners', 'partner-ledger', 'sellers']) {
        queryClient.invalidateQueries({ queryKey: [key] });
      }
      onClose();
    },
  });

  function submit(e: FormEvent) {
    e.preventDefault();
    mutation.mutate();
  }

  return (
    <Modal open title={`${t('newTransaction')}: ${register.name}`} onClose={onClose}>
      <form onSubmit={submit} className="space-y-4">
        <div className="grid grid-cols-2 gap-3">
          <Field label={t('txType')}>
            <Select value={type} onChange={(e) => changeType(e.target.value as typeof type)}>
              {MANUAL_TX_TYPES.map((txType) => (
                <option key={txType} value={txType}>
                  {t(`txTypes.${txType}`)}
                </option>
              ))}
            </Select>
          </Field>
          <Field label={t('category')}>
            <Select required value={category} onChange={(e) => changeCategory(e.target.value)}>
              {CATEGORIES[type].map((c) => (
                <option key={c.value} value={c.value}>
                  {t(`categories.${c.key}`)}
                </option>
              ))}
            </Select>
          </Field>
        </div>

        {isSalary && (
          <>
            <Field label={t('employee')} hint={t('salaryLinkHint')}>
              <Select required value={person} onChange={(e) => changePerson(e.target.value)}>
                <option value="" disabled>
                  {t('selectEmployee')}
                </option>
                {staff.map((p) => (
                  <option key={p.key} value={p.key}>
                    {p.name}
                  </option>
                ))}
              </Select>
            </Field>
            {selectedStaff && (
              <p className="text-xs text-ink-muted">
                {te('payType')}: <span className="font-semibold text-ink">{te(`payTypes.${selectedStaff.payType}`)}</span>
                {selectedStaff.payType === 'FIXED_SALARY' && Number(selectedStaff.salary) > 0 && (
                  <> — {formatMoney(selectedStaff.salary, locale)}</>
                )}
              </p>
            )}
            <Field label={te('period')} hint={te('periodHint')}>
              <Input required dir="ltr" value={period} onChange={(e) => setPeriod(e.target.value)} placeholder="2026-09" />
            </Field>
          </>
        )}

        {isPartner && (
          <Field label={t('partner')}>
            <Select required value={person} onChange={(e) => setPerson(e.target.value)}>
              <option value="" disabled>
                {t('selectPartner')}
              </option>
              {partners
                ?.filter((p) => p.isActive)
                .map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.name}
                  </option>
                ))}
            </Select>
          </Field>
        )}

        <Field label={t('amount')}>
          <Input required type="number" min={0.01} step="0.01" dir="ltr" value={amount} onChange={(e) => setAmount(e.target.value)} />
        </Field>

        {isSalary && (
          <Field label={t('receipt')} hint={t('receiptHint')}>
            <input
              type="file"
              accept="image/jpeg,image/png,image/webp,application/pdf"
              onChange={(e) => setReceipt(e.target.files?.[0] ?? null)}
              className="block w-full cursor-pointer text-sm text-ink-muted file:me-3 file:cursor-pointer file:rounded-lg file:border-0 file:bg-primary-50 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-primary-700"
            />
          </Field>
        )}

        <Field label={t('note')}>
          <Input value={note} onChange={(e) => setNote(e.target.value)} />
        </Field>
        <ErrorText error={mutation.error} />
        <div className="flex gap-2">
          <Button type="submit" loading={mutation.isPending}>
            {tc('save')}
          </Button>
          <Button type="button" variant="ghost" onClick={onClose}>
            {tc('cancel')}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
