'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocale, useTranslations } from 'next-intl';
import { FormEvent, useState } from 'react';
import type {
  CashRegisterDto,
  CashTransactionType,
  EmployeeDto,
  Locale,
  PartnerDto,
  SellerDto,
  WorkSessionDto,
} from '@my-store/shared';
import { api } from '@/lib/api-client';
import { formatMoney } from '@/lib/format';
import { Button, ErrorText, Field, Input, Modal, Select } from '@/components/ui';

/** Manually recordable types — SALE/REFUND are generated by the system */
const MANUAL_TX_TYPES: CashTransactionType[] = ['INCOME', 'EXPENSE', 'WITHDRAWAL'];

/** Paying a person: an employee or seller salary / commission, or a partner payout */
const PERSON_CATEGORY = 'Payment to a person';
const PARTNER_CATEGORY = 'Partner withdrawal';

/** Selectable categories per transaction type — stored as-is in the transaction's category */
const CATEGORIES: Record<'INCOME' | 'EXPENSE' | 'WITHDRAWAL', { value: string; key: string }[]> = {
  INCOME: [
    { value: 'Other income', key: 'otherIncome' },
    { value: 'Capital injection', key: 'capitalInjection' },
    { value: 'Other', key: 'other' },
  ],
  EXPENSE: [
    { value: PERSON_CATEGORY, key: 'person' },
    { value: 'Rent', key: 'rent' },
    { value: 'Utilities', key: 'utilities' },
    { value: 'Transport', key: 'transport' },
    { value: 'Supplies', key: 'supplies' },
    { value: 'Maintenance', key: 'maintenance' },
    { value: 'Marketing', key: 'marketing' },
    { value: 'Taxes & fees', key: 'taxes' },
    { value: 'Other', key: 'other' },
  ],
  WITHDRAWAL: [
    { value: PARTNER_CATEGORY, key: 'partner' },
    { value: 'Owner withdrawal', key: 'owner' },
    { value: 'Other', key: 'other' },
  ],
};

type PersonRole = 'EMPLOYEE' | 'SELLER' | 'PARTNER';

function currentPeriod() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

export function TransactionModal({ register, onClose }: { register: CashRegisterDto; onClose: () => void }) {
  const t = useTranslations('cash');
  const tc = useTranslations('common');
  const te = useTranslations('employees');
  const ts = useTranslations('sessions');
  const locale = useLocale() as Locale;
  const queryClient = useQueryClient();
  const [type, setType] = useState<'INCOME' | 'EXPENSE' | 'WITHDRAWAL'>('EXPENSE');
  const [category, setCategory] = useState(CATEGORIES.EXPENSE[0].value);
  const [amount, setAmount] = useState('');
  const [note, setNote] = useState('');
  const [personRole, setPersonRole] = useState<PersonRole>('EMPLOYEE');
  const [person, setPerson] = useState('');
  const [period, setPeriod] = useState(currentPeriod);
  const [receipt, setReceipt] = useState<File | null>(null);
  /** '' = the main cash box; otherwise the id of an active work session */
  const [paidByChoice, setPaidByChoice] = useState<string | null>(null);

  const isPerson = type === 'EXPENSE' && category === PERSON_CATEGORY;
  const isPartnerWithdrawal = type === 'WITHDRAWAL' && category === PARTNER_CATEGORY;
  const needsPartner = isPartnerWithdrawal || (isPerson && personRole === 'PARTNER');
  /** Plain Income / Withdrawal entries (not a partner payout) can attach a pay slip / receipt */
  const showGenericReceipt = (type === 'INCOME' || type === 'WITHDRAWAL') && !needsPartner;

  const { data: employees } = useQuery({
    queryKey: ['employees'],
    queryFn: () => api.get<EmployeeDto[]>('/employees'),
    enabled: isPerson && personRole === 'EMPLOYEE',
  });
  const { data: sellers } = useQuery({
    queryKey: ['sellers'],
    queryFn: () => api.get<SellerDto[]>('/sellers'),
    enabled: isPerson && personRole === 'SELLER',
  });
  const { data: partners } = useQuery({
    queryKey: ['partners'],
    queryFn: () => api.get<PartnerDto[]>('/partners'),
    enabled: needsPartner,
  });
  // Who pays: the main cash box, or the cash box of a person with an open work session
  const { data: sessions } = useQuery({
    queryKey: ['work-sessions', 'active-for-payment'],
    queryFn: () => api.getPaged<WorkSessionDto[]>('/work-sessions?status=ACTIVE&limit=100').then((r) => r.items),
    retry: false,
  });
  const { data: mine } = useQuery({
    queryKey: ['work-sessions', 'mine'],
    queryFn: () => api.get<WorkSessionDto | null>('/work-sessions/mine'),
    retry: false,
  });
  const paidBy = paidByChoice ?? mine?.id ?? '';

  const people: { key: string; name: string; payType?: string; salary?: string }[] =
    personRole === 'EMPLOYEE'
      ? (employees ?? []).filter((e) => e.isActive).map((e) => ({ key: e.id, name: e.fullName, payType: e.payType, salary: e.salary }))
      : personRole === 'SELLER'
        ? (sellers ?? []).filter((s) => s.isActive).map((s) => ({ key: s.id, name: s.fullName, payType: s.payType, salary: s.fixedSalaryAmount ?? '' }))
        : (partners ?? []).filter((p) => p.isActive).map((p) => ({ key: p.id, name: p.name }));
  const selectedPerson = people.find((p) => p.key === person);

  function changeType(next: 'INCOME' | 'EXPENSE' | 'WITHDRAWAL') {
    setType(next);
    setCategory(CATEGORIES[next][0].value);
    setPerson('');
    setReceipt(null);
  }

  function changePerson(key: string) {
    setPerson(key);
    const found = people.find((p) => p.key === key);
    if (found?.payType === 'FIXED_SALARY' && Number(found.salary) > 0) setAmount(String(Number(found.salary)));
  }

  const mutation = useMutation({
    mutationFn: async () => {
      const sessionId = paidBy === '' ? null : paidBy;
      const common = { amount: Number(amount), note: note || undefined, sessionId };
      if (isPerson && personRole !== 'PARTNER') {
        let receiptImageUrl: string | undefined;
        if (receipt) {
          const form = new FormData();
          form.append('file', receipt);
          receiptImageUrl = (await api.upload<{ url: string }>('/uploads/salary-receipts', form)).url;
        }
        const body = { ...common, period, registerId: register.id, receiptImageUrl };
        return personRole === 'SELLER'
          ? api.post(`/sellers/${person}/salary-payments`, body)
          : api.post(`/employees/${person}/salary-payments`, { ...body, status: 'PAID' });
      }
      if (needsPartner) {
        return api.post(`/partners/${person}/entries`, { type: 'WITHDRAWAL', ...common, registerId: register.id });
      }
      let receiptUrl: string | undefined;
      if (showGenericReceipt && receipt) {
        const form = new FormData();
        form.append('file', receipt);
        receiptUrl = (await api.upload<{ url: string }>('/uploads/cash-receipts', form)).url;
      }
      return api.post(`/cash-registers/${register.id}/transactions`, { type, ...common, category, receiptUrl });
    },
    onSuccess: () => {
      for (const key of [
        'cash-registers', 'cash-transactions', 'salary-payments', 'partners', 'partner-ledger', 'sellers',
        'income-summary', 'work-sessions', 'work-session', 'session-report',
      ]) {
        queryClient.invalidateQueries({ queryKey: [key] });
      }
      onClose();
    },
  });

  function submit(e: FormEvent) {
    e.preventDefault();
    mutation.mutate();
  }

  return (
    <Modal open title={`${t('newTransaction')}: ${t(`parts.${register.part}`)}`} onClose={onClose}>
      <form onSubmit={submit} className="space-y-4">
        <div className="grid grid-cols-2 gap-3">
          <Field label={t('txType')}>
            <Select value={type} onChange={(e) => changeType(e.target.value as typeof type)}>
              {MANUAL_TX_TYPES.map((txType) => (
                <option key={txType} value={txType}>
                  {t(`txTypes.${txType}`)}
                </option>
              ))}
            </Select>
          </Field>
          <Field label={t('category')}>
            <Select
              required
              value={category}
              onChange={(e) => {
                setCategory(e.target.value);
                setPerson('');
              }}
            >
              {CATEGORIES[type].map((c) => (
                <option key={c.value} value={c.value}>
                  {t(`categories.${c.key}`)}
                </option>
              ))}
            </Select>
          </Field>
        </div>

        {isPerson && (
          <Field label={t('personType')}>
            <Select
              value={personRole}
              onChange={(e) => {
                setPersonRole(e.target.value as PersonRole);
                setPerson('');
              }}
            >
              <option value="EMPLOYEE">{ts('roles.EMPLOYEE')}</option>
              <option value="SELLER">{ts('roles.SELLER')}</option>
              <option value="PARTNER">{ts('roles.PARTNER')}</option>
            </Select>
          </Field>
        )}

        {(isPerson || isPartnerWithdrawal) && (
          <>
            <Field label={t('person')} hint={t('personLinkHint')}>
              <Select required value={person} onChange={(e) => changePerson(e.target.value)}>
                <option value="" disabled>
                  {t('selectPerson')}
                </option>
                {people.map((p) => (
                  <option key={p.key} value={p.key}>
                    {p.name}
                  </option>
                ))}
              </Select>
            </Field>
            {selectedPerson?.payType && (
              <p className="text-xs text-ink-muted">
                {te('payType')}: <span className="font-semibold text-ink">{te(`payTypes.${selectedPerson.payType}`)}</span>
                {selectedPerson.payType === 'FIXED_SALARY' && Number(selectedPerson.salary) > 0 && (
                  <> — {formatMoney(selectedPerson.salary ?? 0, locale)}</>
                )}
              </p>
            )}
            {isPerson && personRole !== 'PARTNER' && (
              <Field label={te('period')} hint={te('periodHint')}>
                <Input required dir="ltr" value={period} onChange={(e) => setPeriod(e.target.value)} placeholder="2026-09" />
              </Field>
            )}
          </>
        )}

        <Field label={t('amount')}>
          <Input required type="number" min={0.01} step="0.01" dir="ltr" value={amount} onChange={(e) => setAmount(e.target.value)} />
        </Field>

        <Field label={type === 'INCOME' ? t('receivedBy') : t('paidBy')} hint={t('paidByHint')}>
          <Select value={paidBy} onChange={(e) => setPaidByChoice(e.target.value)}>
            <option value="">{t('mainBox')}</option>
            {(sessions ?? []).map((s) => (
              <option key={s.id} value={s.id}>
                {s.personName} ({ts(`roles.${s.role}`)}) — {s.code}
              </option>
            ))}
          </Select>
        </Field>

        {((isPerson && personRole !== 'PARTNER') || showGenericReceipt) && (
          <Field label={t('receipt')} hint={t('receiptHint')}>
            <input
              type="file"
              accept="image/jpeg,image/png,image/webp,application/pdf"
              onChange={(e) => setReceipt(e.target.files?.[0] ?? null)}
              className="block w-full cursor-pointer text-sm text-ink-muted file:me-3 file:cursor-pointer file:rounded-lg file:border-0 file:bg-primary-50 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-primary-700"
            />
          </Field>
        )}

        <Field label={t('note')}>
          <Input value={note} onChange={(e) => setNote(e.target.value)} />
        </Field>
        <ErrorText error={mutation.error} />
        <div className="flex gap-2">
          <Button type="submit" loading={mutation.isPending}>
            {tc('save')}
          </Button>
          <Button type="button" variant="ghost" onClick={onClose}>
            {tc('cancel')}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
