'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocale, useTranslations } from 'next-intl';
import { FormEvent, useState } from 'react';
import type { CashRegisterDto, CashTransactionType, EmployeeDto, Locale, PartnerDto, SellerDto } from '@my-store/shared';
import { api } from '@/lib/api-client';
import { formatMoney } from '@/lib/format';
import { Button, ErrorText, Field, Input, Modal, Select } from '@/components/ui';

/** Manually recordable types — SALE/REFUND are generated by the system */
const MANUAL_TX_TYPES: CashTransactionType[] = ['INCOME', 'EXPENSE', 'WITHDRAWAL'];

const SALARY_CATEGORY = 'Salary payment';
const PARTNER_CATEGORY = 'Partner withdrawal';

/** Selectable categories per transaction type — stored as-is in the transaction's category */
const CATEGORIES: Record<'INCOME' | 'EXPENSE' | 'WITHDRAWAL', { value: string; key: string }[]> = {
  INCOME: [
    { value: 'Other income', key: 'otherIncome' },
    { value: 'Capital injection', key: 'capitalInjection' },
    { value: 'Other', key: 'other' },
  ],
  EXPENSE: [
    { value: SALARY_CATEGORY, key: 'salary' },
    { value: 'Rent', key: 'rent' },
    { value: 'Utilities', key: 'utilities' },
    { value: 'Transport', key: 'transport' },
    { value: 'Supplies', key: 'supplies' },
    { value: 'Maintenance', key: 'maintenance' },
    { value: 'Marketing', key: 'marketing' },
    { value: 'Taxes & fees', key: 'taxes' },
    { value: 'Other', key: 'other' },
  ],
  WITHDRAWAL: [
    { value: PARTNER_CATEGORY, key: 'partner' },
    { value: 'Owner withdrawal', key: 'owner' },
    { value: 'Other', key: 'other' },
  ],
};

function currentPeriod() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

export function TransactionModal({ register, onClose }: { register: CashRegisterDto; onClose: () => void }) {
  const t = useTranslations('cash');
  const tc = useTranslations('common');
  const te = useTranslations('employees');
  const locale = useLocale() as Locale;
  const queryClient = useQueryClient();
  const [type, setType] = useState<'INCOME' | 'EXPENSE' | 'WITHDRAWAL'>('EXPENSE');
  const [category, setCategory] = useState(CATEGORIES.EXPENSE[0].value);
  const [amount, setAmount] = useState('');
  const [note, setNote] = useState('');
  const [person, setPerson] = useState('');
  const [period, setPeriod] = useState(currentPeriod);
  const [receipt, setReceipt] = useState<File | null>(null);

  const isSalary = type === 'EXPENSE' && category === SALARY_CATEGORY;
  const isPartner = type === 'WITHDRAWAL' && category === PARTNER_CATEGORY;

  const { data: employees } = useQuery({
    queryKey: ['employees'],
    queryFn: () => api.get<EmployeeDto[]>('/employees'),
    enabled: isSalary,
  });
  const { data: sellers } = useQuery({
    queryKey: ['sellers'],
    queryFn: () => api.get<SellerDto[]>('/sellers'),
    enabled: isSalary,
  });
  const { data: partners } = useQuery({
    queryKey: ['partners'],
    queryFn: () => api.get<PartnerDto[]>('/partners'),
    enabled: isPartner,
  });

  const staff = [
    ...(employees ?? [])
      .filter((e) => e.isActive)
      .map((e) => ({ key: `emp:${e.id}`, name: e.fullName, payType: e.payType, salary: e.salary })),
    ...(sellers ?? [])
      .filter((s) => s.isActive && s.payType === 'FIXED_SALARY')
      .map((s) => ({
        key: `sel:${s.id}`,
        name: `${s.fullName} (${t('seller')})`,
        payType: s.payType,
        salary: s.fixedSalaryAmount ?? '',
      })),
  ];
  const selectedStaff = staff.find((p) => p.key === person);

  function changeType(next: 'INCOME' | 'EXPENSE' | 'WITHDRAWAL') {
    setType(next);
    setCategory(CATEGORIES[next][0].value);
    setPerson('');
  }

  function changeCategory(next: string) {
    setCategory(next);
    setPerson('');
  }

  function changePerson(key: string) {
    setPerson(key);
    const found = staff.find((p) => p.key === key);
    if (found && found.payType === 'FIXED_SALARY' && Number(found.salary) > 0) setAmount(String(Number(found.salary)));
  }

  const mutation = useMutation({
    mutationFn: async () => {
      const common = { amount: Number(amount), note: note || undefined };
      if (isSalary) {
        let receiptImageUrl: string | undefined;
        if (receipt) {
          const form = new FormData();
          form.append('file', receipt);
          receiptImageUrl = (await api.upload<{ url: string }>('/uploads/salary-receipts', form)).url;
        }
        const [kind, id] = person.split(':');
        const body = { ...common, period, registerId: register.id, receiptImageUrl };
        return kind === 'sel'
          ? api.post(`/sellers/${id}/salary-payments`, body)
          : api.post(`/employees/${id}/salary-payments`, { ...body, status: 'PAID' });
      }
      if (isPartner) {
        return api.post(`/partners/${person}/entries`, { type: 'WITHDRAWAL', ...common, registerId: register.id });
      }
      return api.post(`/cash-registers/${register.id}/transactions`, { type, ...common, category });
    },
    onSuccess: () => {
      for (const key of ['cash-registers', 'cash-transactions', 'salary-payments', 'partners', 'partner-ledger', 'sellers']) {
        queryClient.invalidateQueries({ queryKey: [key] });
      }
      onClose();
    },
  });

  function submit(e: FormEvent) {
    e.preventDefault();
    mutation.mutate();
  }

  return (
    <Modal open title={`${t('newTransaction')}: ${register.name}`} onClose={onClose}>
      <form onSubmit={submit} className="space-y-4">
        <div className="grid grid-cols-2 gap-3">
          <Field label={t('txType')}>
            <Select value={type} onChange={(e) => changeType(e.target.value as typeof type)}>
              {MANUAL_TX_TYPES.map((txType) => (
                <option key={txType} value={txType}>
                  {t(`txTypes.${txType}`)}
                </option>
              ))}
            </Select>
          </Field>
          <Field label={t('category')}>
            <Select required value={category} onChange={(e) => changeCategory(e.target.value)}>
              {CATEGORIES[type].map((c) => (
                <option key={c.value} value={c.value}>
                  {t(`categories.${c.key}`)}
                </option>
              ))}
            </Select>
          </Field>
        </div>

        {isSalary && (
          <>
            <Field label={t('employee')} hint={t('salaryLinkHint')}>
              <Select required value={person} onChange={(e) => changePerson(e.target.value)}>
                <option value="" disabled>
                  {t('selectEmployee')}
                </option>
                {staff.map((p) => (
                  <option key={p.key} value={p.key}>
                    {p.name}
                  </option>
                ))}
              </Select>
            </Field>
            {selectedStaff && (
              <p className="text-xs text-ink-muted">
                {te('payType')}: <span className="font-semibold text-ink">{te(`payTypes.${selectedStaff.payType}`)}</span>
                {selectedStaff.payType === 'FIXED_SALARY' && Number(selectedStaff.salary) > 0 && (
                  <> — {formatMoney(selectedStaff.salary, locale)}</>
                )}
              </p>
            )}
            <Field label={te('period')} hint={te('periodHint')}>
              <Input required dir="ltr" value={period} onChange={(e) => setPeriod(e.target.value)} placeholder="2026-09" />
            </Field>
          </>
        )}

        {isPartner && (
          <Field label={t('partner')}>
            <Select required value={person} onChange={(e) => setPerson(e.target.value)}>
              <option value="" disabled>
                {t('selectPartner')}
              </option>
              {partners
                ?.filter((p) => p.isActive)
                .map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.name}
                  </option>
                ))}
            </Select>
          </Field>
        )}

        <Field label={t('amount')}>
          <Input required type="number" min={0.01} step="0.01" dir="ltr" value={amount} onChange={(e) => setAmount(e.target.value)} />
        </Field>

        {isSalary && (
          <Field label={t('receipt')} hint={t('receiptHint')}>
            <input
              type="file"
              accept="image/jpeg,image/png,image/webp,application/pdf"
              onChange={(e) => setReceipt(e.target.files?.[0] ?? null)}
              className="block w-full cursor-pointer text-sm text-ink-muted file:me-3 file:cursor-pointer file:rounded-lg file:border-0 file:bg-primary-50 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-primary-700"
            />
          </Field>
        )}

        <Field label={t('note')}>
          <Input value={note} onChange={(e) => setNote(e.target.value)} />
        </Field>
        <ErrorText error={mutation.error} />
        <div className="flex gap-2">
          <Button type="submit" loading={mutation.isPending}>
            {tc('save')}
          </Button>
          <Button type="button" variant="ghost" onClick={onClose}>
            {tc('cancel')}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
